export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "Premium World",
  headLine: "Unlimited items in creating own world",
  description: "Make different items carfting in your own world",
  buttonLabel: "Get Started",
  imgStart: false,
  img: require('../../images/shiping.jpg'),
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjTwo = {
  id: "discover",
  lightBg: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "Premium World",
  headLine: "Unlimited items in creating own world",
  description: "Make different items carfting in your own world",
  buttonLabel: "Get Started",
  imgStart: false,
  img: require('../../images/shiping.jpg'),
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjThree = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Premium World",
  headLine: "Unlimited items in creating own world",
  description: "Make different items carfting in your own world",
  buttonLabel: "Get Started",
  imgStart: true,
  img: require('../../images/shiping.jpg'),
  alt: "hello",
  dark: true,
  primary: true,
  darkText: false,
};